spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitytb?serverTimezone=GMT
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: INFO
    org.springframework.web: debug
    org.springframework.security: debug
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: INFO
    cn.com.taiji.security2: debug

